#!/usr/bin/bash

get_battery_icon()
{
        local bat=$1
        if [[ "$bat" -eq 0 ]]; then
                echo " "
        elif [[ "$bat" -lt 10 ]]; then
                echo "▁"
        elif [[ "$bat" -lt 25 ]]; then
                echo "▂"
        elif [[ "$bat" -lt 40 ]]; then
                echo "▃"
        elif [[ "$bat" -lt 55 ]]; then
                echo "▄"
        elif [[ "$bat" -lt 70 ]]; then
                echo "▅"
        elif [[ "$bat" -lt 85 ]]; then
                echo "▆"
        elif [[ "$bat" -lt 100 ]]; then
                echo "▇"
        else
                echo "█"
        fi
}

if command -v acpi &>/dev/null; then
        battery=$(acpi -b | grep -m 1 -oP '\d+%' | tr -d '%')
        if [[ "$battery" -eq 0 ]]; then
                echo " "
        else
                echo "$(get_battery_icon "$battery")"
        fi

elif command -v upower &>/dev/null; then
        battery=$(acpi -b | grep -m 1 -oP '\d+%' | tr -d '%')
        if [[ "$battery" -eq 0 ]]; then
                echo " "
        else
                echo "$(get_battery_icon "$battery")"
        fi

else
        echo "N/A"
fi
