local M        = {}

-- DIAGNOSTICS
M.diagnostics  = {
        ERROR = "󰨓",
        WARN  = "󰨓",
        HINT  = "󰨓",
        INFO  = "󰨓",
        lightbulb  = "󱠀",
}

-- FOLDING
M.arrows       = {
        close = "+",
        open  = "-",
        right = "",
        left  = "",
        up    = "",
        down  = "",
}

 -- LSP KINDS
M.symbol_kinds = {
        Array             = "󰅪 ",
        Boolean           = " ",
        BreakStatement    = "󰙧 ",
        Call              = "󰃷 ",
        CaseStatement     = "󱃙 ",
        Class             = " ",
        Color             = " ",
        Component         = "󰅴 ",
        Constant          = " ",
        Constructor       = " ",
        ContinueStatement = "→ ",
        Copilot           = " ",
        Declaration       = "󰙠 ",
        Delete            = "󰢤 ",
        DoStatement       = "󰑖 ",
        Enum              = " ",
        EnumMember        = " ",
        Event             = " ",
        Field             = " ",
        File              = " ",
        Folder            = " ",
        ForStatement      = "󰑖 ",
        Fragment          = "󰅴 ",
        Function          = " ",
        H1Marker          = "󰉫 ",
        H2Marker          = "󰉬 ",
        H3Marker          = "󰉭 ",
        H4Marker          = "󰉮 ",
        H5Marker          = "󰉯 ",
        H6Marker          = "󰉰 ",
        Identifier        = " ",
        IfStatement       = " ",
        Interface         = " ",
        Key               = " ",
        Keyword           = " ",
        List              = "󰅪 ",
        Log               = " ",
        Lsp               = " ",
        Macro             = " ",
        MarkdownH1        = "󰉫 ",
        MarkdownH2        = "󰉬 ",
        MarkdownH3        = "󰉭 ",
        MarkdownH4        = "󰉮 ",
        MarkdownH5        = "󰉯 ",
        MarkdownH6        = "󰉰 ",
        Method            = " ",
        Module            = " ",
        Namespace         = " ",
        Null              = "󰢤 ",
        Number            = "󰎠 ",
        Object            = " ",
        Operator          = " ",
        Package           = " ",
        Pair              = "󰅪 ",
        Parameter         = " ",
        Property          = " ",
        Reference         = " ",
        Regex             = " ",
        Repeat            = "󰑖 ",
        Scope             = " ",
        Snippet           = " ",
        Specifier         = "󰦪 ",
        Statement         = " ",
        StaticMethod      = " ",
        String            = "󰉾 ",
        Struct            = " ",
        SwitchStatement   = "󰺟 ",
        Terminal          = " ",
        Text              = " ",
        Type              = " ",
        TypeAlias         = " ",
        TypeParameter     = " ",
        Unit              = " ",
        Value             = " ",
        Variable          = " ",
        WhileStatement    = "󰑖 ",
}

-- MISC
M.misc         = {
        bug          = "",
        ellipsis     = "…",
        Variable     = "",
        git          = "",
        search       = "",
        vertical_bar = "▏",
        dashed_bar   = "󰨕",
}

return M
